<%@ page contentType="text/html;charset=UTF-8" %>

<div class="row column margin-top-large">
    <div class="media-object">
        <div class="media-object-section middle hide-for-small-only padding-right-xlarge">
            <div class="thumbnail">
                <img alt="Human Cell Atlas" style="max-width: 275px"
                     src="${pageContext.request.contextPath}/resources/images/logos/human_cell_atlas.png"/>
            </div>
        </div>
        <div class="media-object-section middle">
            <h4>
                The Hinxton Portal of the Human Cell Atlas is a joint initiative between groups at EMBL-EBI and the
                Sanger Institute. The project analyses, visualises and provides tools for exploration and further
                analysis of single cell RNA-Seq data generated by the Human Cell Atlas, as well as other projects
                on human tissue.
            </h4>
        </div>
    </div>
</div>

<div class="row column margin-top-xlarge">
    <%@ include file="hca-landing-page/data.jsp" %>
</div>

<div class="row column margin-top-large">
    <%@ include file="hca-landing-page/tools.jsp" %>
</div>

<div class="row column margin-top-large">
    <%@ include file="hca-landing-page/people.jsp" %>
</div>


