-- Table for storing marker gene probabilities
DROP TABLE SCA_MARKER_GENES CASCADE;
CREATE TABLE SCA_MARKER_GENES (
    GENE_ID CHARACTER VARYING (255) NOT NULL,
    EXPERIMENT_ACCESSION CHARACTER VARYING (255) NOT NULL,
    K INTEGER NOT NULL,
    CLUSTER_ID INTEGER NOT NULL,
    MARKER_PROBABILITY FLOAT(53),
    PRIMARY KEY (GENE_ID, EXPERIMENT_ACCESSION, K, CLUSTER_ID)
);
