-- Table for storing single cell expression levels
DROP TABLE SINGLE_CELL_EXPRESSION CASCADE;
CREATE TABLE SINGLE_CELL_EXPRESSION (
    EXPERIMENT_ACCESSION VARCHAR(255) NOT NULL,
    GENE_ID VARCHAR(255) NOT NULL,
    CELL_ID  VARCHAR(255) NOT NULL,
    EXPRESSION_LEVEL FLOAT(35),
    PRIMARY KEY (EXPERIMENT_ACCESSION, GENE_ID, CELL_ID)
);